image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=88 --exclude src/txtferret/_default.py src/*

pytest:
  stage: Test
  script:
    - pwd
    - ls -l
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/src
    - echo $PYTHONPATH
    - python -c "import sys;print(sys.path)"
    - pytest tests/
