name: TxtFerret Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
   
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --count --exclude src/txtferret/_default.py --max-line-length=88 --statistics --exit-zero src/*
        
    - name: Security scan with Bandit
      run: |
        pip install bandit
        bandit -r -x src/txtferret/_default.py src/*

    - name: Test with pytest
      run: |
        echo "Setting python path"
        export PYTHONPATH=$(pwd)/src
        echo $PYTHONPATH
        pip install pytest
        pytest tests/*
